Создан проект по лекцияс 1, 2, 3.
simt11/MyTelegram pull request #1
Opened 2022-12-16 11:40 UTC by simt11

1) Библиотеки mikepenza drawematerial установлены версии 7.0.0 2) в gradle добавлено
    def lifecycle_version = "2.4.0"
    implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
  для снятия конфликта.
3) В тему добавлено
     <item name="windowActionBar">false</item> не запрашивать функцию окна
     <item name="windowNoTitle">true</item> Разрешаем заголовок
4) Создан Toolbar
5) Боковое меню наполнено  пунктами с иконками.

2022-12-16 14:06 UTC, fantasianna approved these changes

2022-12-16 14:06 UTC, fantasianna commented on app/src/main/res/layout/activity_main.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
ConstraintLayout +++

2022-12-16 14:06 UTC, fantasianna commented on app/src/main/res/layout/activity_main.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
классно я имею ввиду))

2022-12-16 14:06 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/MainActivity.kt
> +        initFields()
отрада глаз моих такие названия функций!

2022-12-16 14:06 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/MainActivity.kt
> +                ProfileDrawerItem().withName("Vova B")
эти строки надо сразу вынести в ресурсы string.xml. Я в прошлом проекте скидывала ссылку на инструкцию про строковые ресурсы

2022-12-16 14:06 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/MainActivity.kt
> +    private fun initFunc() {
название методы все-таки не очень понятное, типа инициализирует Func. Но кто такой Func и как он относится к тому что происходит сейчас внутри метода - нипанятна

2022-12-16 14:06 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/MainActivity.kt
> +        drawer = DrawerBuilder()
это билдер для бокового меню?

2022-12-16 14:06 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/MainActivity.kt
> +                    .withName("Создать группу")
все магические строки нужно отправить в strings.xml

2022-12-16 14:06 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/MainActivity.kt
> +                PrimaryDrawerItem().withIdentifier(101)
а все магические цифры нужно вынести в приватные константы этого файла

2022-12-16 14:08 UTC, fantasianna requested changes
Глянь комменты пожалуйста

2022-12-17 18:45 UTC, simt11 commented on app/src/main/java/com/example/mytelegram/MainActivity.kt
> +        drawer = DrawerBuilder()
Ага)

2022-12-19 11:37 UTC, fantasianna approved these changes

2022-12-19 11:38 UTC, closed without merging