Lesson 5
simt11/MyTelegram pull request #2
Opened 2022-12-19 11:31 UTC by simt11

2022-12-21 08:50 UTC, fantasianna requested changes

2022-12-21 08:50 UTC, fantasianna commented on app/build.gradle
> +    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1"
тут хорошо было, что номер версии один и через константу lifecycle_version
если ты хотела поднять номер зависимости для lifecycle-viewmodel-ktx, то лучше поднять именно lifecycle_version, чтобы у этих двух зависимостей был одинаковый номер версии

2022-12-21 08:50 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/ui/fragments/BaseFragment.kt
> +open class BaseFragment(val layout: Int) : Fragment() {
хорошее решение с бащовым фрагментом

2022-12-21 08:50 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/ui/objects/AppDrawer.kt
> +private const val id_create_groups: Long     = 1
да классно! только мини уточнение, что по код стайлу обычно константы большими буквами именуются, в твоем случае это будет ID_CREATE_GROUPS

2022-12-21 08:50 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/ui/objects/AppDrawer.kt
> +private const val id_help: Long              = 9
тут надо добавить пустую строку, а то сливается

2022-12-21 08:50 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/ui/objects/AppDrawer.kt
> +        createHeader()
красиво!

2022-12-21 08:50 UTC, fantasianna commented on app/src/main/res/layout/activity_main.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
ConstraintLayout внутри ConstraintLayout не особо хорошо. ConstraintLayout нуден для того чтобы внутри него расположить все элементы. Мы всегда стараемся избегать вложенности элементов друг в дурга насколько это возможно

2022-12-21 08:50 UTC, fantasianna commented on app/src/main/res/layout/fragment_settings.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
постарайся избавиться от вложенных ConstraintLayout

2022-12-21 08:50 UTC, fantasianna commented on app/src/main/res/layout/fragment_settings.xml
> +            android:textSize="@dimen/TextH2"
отлично, что размеры сразу через dimen, даже похоже на дизайн систему

2022-12-21 08:50 UTC, fantasianna commented on app/src/main/res/layout/fragment_settings.xml
> +            android:id="@+id/textView2"
нужно стараться по максимум избегать названий переменных с цифрами. Если это только возможно лучше называть по смыслу

2022-12-21 12:39 UTC, simt11 commented on app/src/main/res/layout/activity_main.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
У меня в этот контейнер открываются фрагменты. Как можно по другому?

2022-12-21 13:03 UTC, simt11 commented on app/src/main/res/layout/activity_main.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
Разобрался

2023-01-10 08:47 UTC, fantasianna approved these changes

2023-01-10 09:15 UTC, merged