Lesson 7
simt11/MyTelegram pull request #4
Opened 2023-01-09 10:31 UTC by simt11

Добавлено окно регистрации

2023-01-11 12:55 UTC, fantasianna commented
добавь плиз все файлы внутри .idea в гит игнор, чтобы они не отправлялись каждый раз, они нужны тебе только локально, их не надо отправлять в репозиторий https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000154070-How-to-gitignore-idea-files

2023-01-11 15:26 UTC, fantasianna requested changes

2023-01-11 15:26 UTC, fantasianna commented on app/build.gradle
> +    implementation "androidx.lifecycle:lifecycle-viewmodel:2.5.1"
тут как раз было бы хорошо добавить def lifecycle_version = "2.5.1" и далее использовать lifecycle_version для двух этих зависимостей

2023-01-11 15:26 UTC, fantasianna commented on app/src/main/AndroidManifest.xml
> +            <intent-filter>
класс, а ты почитал, что делают интент фильтры? это популярный и мощный механизм

2023-01-11 15:26 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/MainActivity.kt
> +        if (false) {
что????

2023-01-11 15:26 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/ui/fragments/BaseFragment.kt
> +    override fun onStart() {
если там дальше кода нет, то можно удалить этот метод. Если там что-то ожидается в будущем, то можно добавить тудушку

2023-01-11 15:26 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/ui/fragments/ChatsFragment.kt
> +        super.onResume()
тут то же что и выше

2023-01-11 15:26 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/ui/fragments/EnterPhoneNumberFragment.kt
> +                ?.addToBackStack(null)
а что значит null тут в параметре?

2023-01-11 15:26 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/ui/objects/AppDrawer.kt
> +private const val id_create_groups: Long     = 1
а, надо дев сюда накатить, чтобы накатились твои старые фиксы

2023-01-12 06:51 UTC, simt11 commented on app/src/main/AndroidManifest.xml
> +            <intent-filter>
Не читал. Из урока понял, что здесь мы не даем высплывающей клавиатуре перекрыть нижнюю кнопку. Почитаю :)

2023-01-12 07:27 UTC, simt11 commented on app/src/main/AndroidManifest.xml
> +            <intent-filter>
Теперь почитал) Интересный механизм)

2023-01-12 08:37 UTC, simt11 commented on app/src/main/java/com/example/mytelegram/MainActivity.kt
> +        if (false) {
В этой лекции реализуется окно регистрации. При условии, что проверка по безе не зафиксирована (false), в следующих уроках уже это реализуется

2023-01-12 08:59 UTC, simt11 commented on app/src/main/java/com/example/mytelegram/ui/fragments/EnterPhoneNumberFragment.kt
> +                ?.addToBackStack(null)
Я не могу дать точного ответа. Как я понял, создается возможность вернуться на этот экран из следующего. При этом в стеке ничего не будет.

2023-01-12 10:45 UTC, fantasianna approved these changes
все хорошо, обрати внимание на комменты

2023-01-12 10:45 UTC, fantasianna commented on app/build.gradle
> +    def materialdrawer_version = "7.0.0"
красивое!

2023-01-12 10:45 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/ui/fragments/EnterPhoneNumberFragment.kt
> +                ?.addToBackStack(null)
почитай внимательно еще раз вот эту статью https://developer.alexanderklimov.ru/android/theory/fragments.php

2023-01-23 08:55 UTC, merged