Lesson 10
simt11/MyTelegram pull request #8
Opened 2023-01-12 12:34 UTC by simt11

Добавлена база данных с возможностью авторизации по номеру телефона и подтверждением через смс
Ввод номера телефона:
![Screenshot_20230112_150616](https://user-images.githubusercontent.com/25998931/212067507-03b7f94d-5d8a-471b-b304-afd6b914dc98.png)

Ввод проверочного кода:
![Screenshot_20230112_150858](https://user-images.githubusercontent.com/25998931/212067562-3a738875-1c33-4d1b-abd0-d740a0cbb436.png)

2023-01-26 13:34 UTC, fantasianna requested changes

2023-01-26 13:34 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/utilits/firebaseHelper.kt
> +lateinit var AUTH:FirebaseAuth
лучше придерживаться единого стиля именования файлов исходного кода и называть их всегда с заглавный буквы. Касается firebaseHelper.kt и fun.kt

2023-01-26 13:34 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/ui/fragments/EnterPhoneNumberFragment.kt
> +        callback = object: PhoneAuthProvider.OnVerificationStateChangedCallbacks(){
вот тут возможна утечка памяти, если пользователю поверх твоего экрана открылся другой экран или диалоговое окно или системное окно (например ему кто-то позвонил). Тема сложная, но ты уже достаточно опытный, чтобы начать в нее погружаться. Почитай вот тут https://developer.alexanderklimov.ru/android/debug/memory_leak.php, твой кейс близок к случаю "Утечка с таймерами". Чтобы избежать утечки, тебе надо в зеркальном для onStart коллбеке **onStop** занулить перенеменную callback

2023-01-26 13:34 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/ui/fragments/EnterPhoneNumberFragment.kt
> +                        showToast(task.exception?.message.toString())
тут тип ексепшена не FirebaseException? если да, то можно переиспользовать метод onVerificationFailed

2023-01-26 13:52 UTC, simt11 commented on app/src/main/java/com/example/mytelegram/ui/fragments/EnterPhoneNumberFragment.kt
> +                        showToast(task.exception?.message.toString())
Так, я не очень понял что ты хочешь сказать этим комментарием (((

2023-01-26 13:52 UTC, simt11 commented on app/src/main/java/com/example/mytelegram/ui/fragments/EnterPhoneNumberFragment.kt
> +        callback = object: PhoneAuthProvider.OnVerificationStateChangedCallbacks(){
Ок, сегодня прочту

2023-01-26 14:26 UTC, fantasianna requested changes

2023-01-26 14:26 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/ui/fragments/EnterPhoneNumberFragment.kt
> +                        showToast(task.exception?.message.toString())
а, я не увидела, что onVerificationFailed это коллбэк, а не просто метод, тогда вопрос снят

2023-02-06 14:08 UTC, simt11 commented on app/src/main/java/com/example/mytelegram/ui/fragments/EnterPhoneNumberFragment.kt
> +        callback = object: PhoneAuthProvider.OnVerificationStateChangedCallbacks(){
Callback нельзя сделать null, его тип не нулевой. Как по другому сделать, моих знаний и понимания не хватает

2023-02-07 11:09 UTC, fantasianna approved these changes

2023-02-07 11:09 UTC, fantasianna commented on app/src/main/java/com/example/mytelegram/ui/fragments/EnterPhoneNumberFragment.kt
> +        callback = object: PhoneAuthProvider.OnVerificationStateChangedCallbacks(){
ок ладно, пусть так пока будет, это не особо критично

2023-02-07 11:09 UTC, merged